name = "snapskillz"
compatibility_date = "2024-09-02"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages configuration
pages_build_output_dir = "dist"

[env.production.vars]
# Add any production environment variables here
# EXAMPLE_VAR = "production_value"

[env.preview.vars]
# Add any preview environment variables here
# EXAMPLE_VAR = "preview_value"